# Generated by Django 4.2.2 on 2023-07-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descub', '0002_alter_muralista_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mural',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos_murales/'),
        ),
    ]
