# Generated by Django 4.2.2 on 2023-07-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descub', '0003_alter_mural_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mural',
            name='imagen',
        ),
        migrations.AddField(
            model_name='mural',
            name='imagen1',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='mural',
            name='imagen2',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='mural',
            name='imagen3',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='muralista',
            name='foto',
            field=models.BinaryField(max_length=10485760, null=True),
        ),
    ]
